
ALTER TABLE public.students 
ADD COLUMN IF NOT EXISTS admission_year TEXT,
ADD COLUMN IF NOT EXISTS sage_customer_id TEXT,
ADD COLUMN IF NOT EXISTS imply_pta BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_last_child BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS state_of_origin TEXT,
ADD COLUMN IF NOT EXISTS lga TEXT,
ADD COLUMN IF NOT EXISTS permanent_address TEXT,
ADD COLUMN IF NOT EXISTS boarding_status TEXT DEFAULT 'Day',
ADD COLUMN IF NOT EXISTS height TEXT,
ADD COLUMN IF NOT EXISTS weight TEXT,
ADD COLUMN IF NOT EXISTS student_email TEXT;
