-- URGENT: Disable Row-Level Security on all tables to restore data access immediately.
ALTER TABLE public.term_results_audit DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.terms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sub_terms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.students DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_class_subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbt_tests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbt_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.term_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
